# Generated by Django 4.1.7 on 2023-02-24 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Measurement',
            new_name='Measurment',
        ),
    ]
